### ISSUE TITLE
Frontalize face to a specific angle

### ISSUE THREAD

**Issue by Mayur28** [YuYin1/DA-GAN#9]
Hi,

I am really amazed by the results achieved!

I just wanted to find out if there is any way that one can specify the degree to which the face should be rotated (in the case one would require the face to be aligned near-frontal such as 10°).

Thanks.

**Comment by YuYin1** [comment]
No, you can not do it in this project.

**Comment by Mayur28** [comment]
Thanks

**Comment by Hambirepurva29** [comment]
> Hi,
> 
> I am really amazed by the results achieved!
> 
> I just wanted to find out if there is any way that one can specify the degree to which the face should be rotated (in the case one would require the face to be aligned near-frontal such as 10°).
> 
> Thanks.

From where did you get the dataset ie. multipie file 
How did you arrange it in the folder?
Please provide the dataset well-arranged folder
